### ISSUE TITLE
 Shopping list web application

### ISSUE THREAD

**Issue by HopeIvy12** [SchoolOfCode/week-2-debugging-team11#1]
```[tasklist]
### Tasks
- [x] Page is unstyled - the "Add" button should be green
- [x] Page styling works properly.
- [x] Page is not interactive - clicking "Add" does nothing, even though JavaScript handles interactivity.
- [x] when we add item its not listing
- [x] Page becomes fully interactive (adding items to list works).
```
